name: Update submodules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
          fetch-depth: 0

      - name: update submodule
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git submodule update --remote
          git commit -am "update submodule" || echo "no changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
